### ISSUE TITLE
Kernel Interpolation usage

### ISSUE THREAD

**Issue by K-H-Ismail** [XuRuihan/ParCNetV2#1]
Hello,
I am going through ParCNet V2 code and it seems that the kernel interpolation introduced in the section **Adaptability to multi-scale input** of the paper is never used (at least in classification). 

https://github.com/XuRuihan/ParCNetV2/blob/52683653a33177128e01935282d93dd79c06f0a5/models/parcnetv2.py#L73

Could you please tell me if it is useful ? Did you use it during training ? For downstream tasks ?

Thanks.

**Comment by XuRuihan** [comment]
1. Yes, the kernel interpolation is useful when you turn on the `interpolate`. It makes the model invariant to resolution changes and benefits from multi-scale input.
2. In ImageNet classification, all the input has the same input resolution, thus it does not make any difference for this task.
3. For the downstream tasks, we found that in semantic segmentation, kernel interpolation reach high performance with single-scale testing, while cannot benefit from multi-scale testing. It is because interpolation treats the multi-scale inputs equivalently, thus there is no improvement. Given that the multi-scale testing is a common practice in semantic segmentation, we shut down this operation for a fair comparison. If you use multi-scale training and single-scale testing, we suggest `interpolate=True` to achieve a better results.

**Comment by K-H-Ismail** [comment]
Understood. Thank you for your help !
